name: Dummy Workflow

on:
  push:
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate workflow
        run: echo "Dummy workflow triggered on push or pull request"
